kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Chart.Name }}
  annotations:
    description: Defines how to build the application
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.source.uri }}
      ref: 
    contextDir: 
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: "openshift"
        name: nodejs:10
      env:
      - name: NPM_MIRROR
        value: 
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Chart.Name }}:latest
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: GitHub
    github:
      secret: "cS3AFvpd1DLz7C0VW5OVmJhTnXM0qwuOy4JFtulV"
  - type: Generic
    generic:
      secret: "gUE5VbKpAmDhz0dYMx5VkZUGK31jQxgE2uOfazNv"
  postCommit:
    script: npm test
