kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Chart.Name }}
  annotations:
    description: Defines how to deploy the application server
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  strategy:
    type: Rolling
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Chart.Name }}
      from:
        kind: ImageStreamTag
        name: {{ .Chart.Name }}:latest
  - type: ConfigChange
  replicas: {{ .Values.deployment.replicas }}
  selector:
    name: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        name: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: " "
        ports:
        - containerPort: {{ .Values.service.port }}
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/"
            port: {{ .Values.service.port }}
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/"
            port: {{ .Values.service.port }}
        resources:
          limits:
            memory: {{ .Values.deployment.resources.memory }}